---
title: "SEIR"
output: html_notebook
---
## Modelo

Nós usamos um modelo epidemiológico compartimental, baseado no clássico modelo SEIR, para descrever a propagação e progressão clínica do COVID-19. Uma boa introdução para este tipo de modelo está disponível na [Wikipedia](https://en.wikipedia.org/wiki/Compartmental_models_in_epidemiology).  É importante registrar os diferentes desfechos clínicos da infecção, pois requerem diferentes quantidades de recursos hospitalares para serem tratados e podem ser testados e isolados em diferentes taxas.. Indivíduos Suscetíveis ($S$) que se tornam infectados começam em uma classe exposta $E$, onde eles são assintomáticos e não transmitem a infecção. A taxa de progresso do estágio exposto para o estágio infectado $I$, onde o indivíduo é sintomático e infeccioso, ocorre em uma taxa $a$. As descrições clínicas dos diferentes estágios de infeccção são dados abaixo. Indivíduos infectados começam com uma infecção *leve* ($I_1$), de onde eles podem ou se recuperar, em uma taxa $\gamma_1$, ou progredirem a uma infecção *severa* ($I_2$), em uma taxa $p_1$. Infecções severas se recuperam em uma taxa $\gamma_2$ ou progridem a um estágio crítico ($I_3$) em uma taxa $p_2$. Indivíduos com infecções críticas se recuperam em uma taxa $\gamma_3$ e morrem em uma taxa $\mu$. Indivíduos recuperados são registrados pela classe $R$ e supõe-se que estão protegidos de re-infecções para o resto da vida. Indivíduos podem transmitir a infecção em qualquer etapa, porém com diferentes taxas. A taxa de transmissão no estágio $i$ é descrita por $\beta_i$ . 
 
### Equações

\begin{equation}
\dot{S} = -\beta_1 I_1 S -\beta_2 I_2 S - \beta_3 I_3 S
\end{equation}

\begin{equation}
\dot{E} =\beta_1 I_1 S +\beta_2 I_2 S + \beta_3 I_3 S - a E \\
\end{equation}

\begin{equation}
\dot{I_1} = a E - \gamma_1 I_1 - p_1 I_1 \\
\end{equation}

\begin{equation}
\dot{I_2} = p_1 I_1 -\gamma_2 I_2 - p_2 I_2 \\
\end{equation}

\begin{equation}
\dot{I_3}  = p_2 I_2 -\gamma_3 I_3 - \mu I_3 \\
\end{equation}

\begin{equation}
\dot{R}  = \gamma_1 I_1 + \gamma_2 I_2 + \gamma_3 I_3 \\
\end{equation}

\begin{equation}
\dot{D}  = \mu I_3
\end{equation}



### Variáveis
* $S$: Indivíduos Suscetíveis
* $E$: Indivíduos Expostos - infectados mas ainda não infecciosos ou sintomáticos
* $I_i$: Indivíduos infectados na classe de gravidade $i$. Gravidade aumenta com $i$ e presumimos que indivíduos devem passar por todas as classes prévias
  * $I_1$: Infecção leve 
  * $I_2$: Infecção grave 
  * $I_3$: Infecção crítica 
* $R$: indivíduos que se recuperaram da doença e estão agora imunes
* $D$: Indivíduos falecidos
* $N=S+E+I_1+I_2+I_3+R+D$ Tamanho total da população (constante)

### Parâmetros
* $\beta_i$ taxa em que indivíduos infectados em uma classe $I_i$ entram em contato com suscetíveis e os infeccionam
* $a$ taxa de progressão da classe exposta até a infectada
* $\gamma_i$ taxa em que indivíduos infectados em uma classe $I_i$ se recuperam da doença e se tornam imunes
* $p_i$ taxa em que indivíduos infectados em uma classe $I_i$ progridem a uma classe $I_{i+1}$
* $\mu$ taxa de mortalidade para indivíduos no estágio mais grave da doença

### Estágios clínicos

* Infecção leve - Estes indivíduos possuem sintomas como febre e tosse e podem apresentar pneumonia leve. Não é necessária hospitalização (apesar de em muitos países tais indivíduos também estarem hospitalizados)
* Infecção grave - Estes indivíduos apresentam pneumonia mais grave que leva a dispneia, frequência respiratória <30/min, saturação de oxigênio sanguíneo <93%, razão entre pressão parcial de oxigênio arterial e fração de oxigênio inspirado <300, e/ou infiltração pulmonar >50% dentro de 24 a 48 horas. Internação e suplementação de oxigênio normalmente são necessárias.
* Infecção crítica - Estes indivíduos apresentam insuficiência respiratória, choque séptico, e/ou disfunção ou falência múltipla dos orgãos. Tratamento em UTI, frequentemente com ventilação mecânica, é necessário.


### Relacionando observações clínicas a parâmetros de modelagem

Para determinar os parâmetros de modelagem de acordo com dados clínicos atuais, coletamos os seguintes valores dos valores do slider determinados pelo usuário, e então utilizamos as formulas abaixo para relacionar-los com os parâmetros de taxa no modelo. Note que os inputs do slider para intervalos de tempo são durações em média.

* IncubPeriod:  Período de incubação médio, em dias
* DurMildInf: Duração média de infecções leves, em dias
* FracMild: Fração média de infecções (sintomáticas) que são leves
* FracSevere: Fração média de infecções (sintomáticas) que são graves
* FracCritical: Fração média de infecções (sintomáticas) que são críticas
* CFR: Case fatality rate / Taxa de fatalidade de casos (fração de infecções que eventualmente resultam em óbito)
* DurHosp: Duração média de hospitalização para indivíduso com infecções graves/críticas, em dias
* TimeICUDeath: Tempo médio que leva de uma internação em UTI até óbito, em dias

(Note g=$\gamma$)
```{r}
a=1/IncubPeriod

g1=(1/DurMildInf)*FracMild
p1=(1/DurMildInf)-g1

p2=(1/DurHosp)*(FracCritical/(FracSevere+FracCritical))
g2=(1/DurHosp)-p2

u=(1/TimeICUDeath)*(CFR/FracCritical)
g3=(1/TimeICUDeath)-u

```


### Taxa reprodutiva básica

Ideia: $R_0$ é a soma de 
1. o número médio de infecções secundárias geradas a partir de um indivíduo no estágio $I_1$
2. a probabilidade de um indivíduo infectado progredir para $I_2$ multiplicado pelo número médio de infecções secundárias geradas a partir de um indivíduo no estágio $I_2$
3.  a probabilidade de um indivíduo infectado progredir para  $I_3$ multiplicado pelo número médio de infecções secundárias geradas a partir de um indivíduo no estágio $I_3$

\begin{equation}
R_0  = N\frac{\beta_1}{p_1+\gamma_1} + \frac{p_1}{p_1 + \gamma_1} \left( \frac{N \beta_2}{p_2+\gamma_2} + \frac{p_2}{p_2 + \gamma_2} \frac{N \beta_3}{\mu+\gamma_3}\right)
\end{equation}

\begin{equation}
 = N\frac{\beta_1}{p_1+\gamma_1} \left(1 + \frac{p_1}{p_2 + \gamma_2}\frac{\beta_2}{\beta_1} \left( 1 + \frac{p_2}{\mu + \gamma_3} \frac{\beta_3}{\beta_2} \right) \right)
\end{equation}

Cálculos usando a matriz de próxima geração fornecem os mesmos resultados. 

### Taxa de crescimento epidêmico cedo

No começo da epidemia, antes de indivíduos suscetíveis serem esgotados, a epidemia cresce em uma taxa exponencial $r$, que também pode ser descrita com tempo de duplicação T$_2$=ln(2)$/r$. Durante essa fase todas as classes infectadas crescem na mesma taxa.

### Presunções

* Esse modelo é formulado como um sistema de equações diferenciais e o resultado portanto representa os valores esperados de cada quantidade. Ele não leva em conta eventos estocáticos ou relata a variância esperada nas variáveis, que pode ser grande. 
* Indivíduos devem passar por um estágio leve antes de atingirem um estado grave ou crítico
* Indivíduos devem passar por um estágio grave antes de atingirem um estado crítico
* Apenas indíviduos em estágio crítico morrem
* 

