worst:
    nothing: 
        R0: 3.97
    isolation: 
        R0: 1.31
    lockdown:
        R0: 0.37
    test_delay: 15
      
best:
    nothing:
        R0: 3.74
    isolation:
        R0: 1.21
    lockdown:
        R0: 0.28
    test_delay: 15