infected:
    i1_percentage: 0.855
    i2_percentage: 0.125
    i3_percentage: 0.025
    
exposed:
    doubling_rate: 1.26
    
# scenarios:
#     nothing: 
#         R0:
#             lower_bound: 3.74
#             upper_bound: 3.97
#     isolation: 
#         R0: 
#             lower_bound: 1.21
#             upper_bound: 1.31
#         dates: [1, 2, 3, 5, 7, 14, 21, 60, 90]
#     lockdown:
#         R0:
#             lower_bound: 0.28
#             upper_bound: 0.37
#         dates: [1, 2, 3, 5, 7, 14, 21, 60, 90]