---
bibliography: references.bib
output:
  html_document:
    df_print: paged
---

## Descrição e fontes para parâmetros de simulação

### Estrutura do modelo

A estrutura básica do modelo é inspirada em muitos estudos sobre a progressão clínica natural da infecção por COVID-19. Para um bom resumo, consulte [@wu_characteristics_2020]. Os indivíduos infectados não desenvolvem sintomas graves imediatamente, mas passam primeiro pelas fases mais leves da infecção. Em alguns estudos, o que chamamos de infecções *leves* são agrupadas em duas categorias diferentes, *leve* e *moderada*, em que indivíduos com infecção *moderada* apresentam sinais radiográficos de pneumonia leve. Esses casos *leves* e *moderados* ocorrem em proporções aproximadamente iguais (por ex. veja @yang_epidemiological_2020). Há algum debate sobre o papel da transmissão pré-sintomática (que ocorre no estágio exposto) e a infecção e transmissão assintomáticas do COVID-19. A versão atual do modelo não inclui esses efeitos.

### Parâmetros do modelo dinâmico

O comportamento do modelo dinâmico é determinado por um conjunto de parâmetros de taxa, incluindo as taxas de transmissão $\beta_i$, as taxas de progressão $a$ and $p_i$, as taxas de recuperação $\gamma_i$, e a taxa de mortalidade $\mu$. Embora essas taxas em si geralmente não sejam medidas diretamente nos estudos, outras quantidades mensuráveis podem ser usadas para recuperar esses parâmetros de taxa.

O tempo gasto na classe exposta é chamado de *período de incubação*  e geralmente é considerado igual ao tempo entre a exposição a uma fonte infectada e o desenvolvimento de sintomas. No modelo, o período médio de incubação é de $1/a$. 

O *período infeccioso* é o tempo durante o qual um indivíduo pode transmitir a outros. Em nosso modelo, há potencialmente três períodos infecciosos diferentes, ocorrendo durante cada estágio clínico da infecção ($I_1$, $I_2$, $I_3$). Precisamos saber a duração de cada uma dessas etapas. Acreditamos que é provável que um indivíduo seja mais infeccioso durante o estágio de infecção leve, quando ainda estaria na comunidade e se sentindo bem o suficiente para interagir com outros, mas no modelo também há a opção de transmissão nos outros estágios, por exemplo, transmissão de pacientes hospitalizados para seus profissionais de saúde. Em nível populacional, esperamos que a maior parte da transmissão ocorra a partir desses indivíduos com infecção leve, uma vez que a maioria dos pacientes não progride além desse estágio. Para o COVID-19, podemos estimar a duração do primeiro estágio de a) a duração dos sintomas leves, b) o tempo desde o início dos sintomas até a hospitalização (por exemplo, progresso para o estágio grave) ou c) a duração do derramamento viral por escarro ou esfregaços na garganta, d) o intervalo serial entre o início dos sintomas em um caso índice e um caso secundário que eles infectam. No modelo, as quantidades a)-c) são iguais a $1/(p_1 + \gamma_1)$, enquanto d) é $1/a + (1/2) 1/(p_1 + \gamma_1)$. Essas estimativas convergem em valores semelhantes para $p_1+\gamma_1$.  A probabilidade de progredir para o estágio grave é igual à proporção de todas as infecções que acabam sendo graves ou críticas e deve ser igual à combinação de parâmetros $p_1/(p_1+\gamma_1)$. 

Indivíduos com infecção grave ($I_2$) requerem hospitalização. A duração das infecções graves, que podem ser relatadas como o tempo entre a internação e a recuperação de indivíduos que não progrediram para o estágio crítico, ou o tempo entre a internação e a internação na UTI (uma vez que casos críticos requerem cuidados no nível da UTI), para os parâmetros do modelo $1/(p_2+\gamma_2)$. Como não existem estimativas diretas dessa duração, utilizamos estimativas do tempo total desde o início dos sintomas até a admissão na UTI (por exemplo, duração combinada de infecção leve + grave) e subtraímos a duração inferida da infecção leve. Em seguida, usamos a probabilidade observada de progredir para infecção crítica, igual à proporção de infecções críticas para críticas + graves, que é igual a $p_2/(p_2 + \gamma_2$), para resolver separadamente $p_2$ e $\gamma_2$. No estágio crítico da infecção ($I_3$) Cuidados na UTI, geralmente com ventilação mecânica, são necessários. A duração deste estágio da infecção, p. o tempo entre a admissão na UTI e a recuperação ou morte é igual a $1/(\gamma_3 + \mu$) mas nem sempre são relatados. Em vez disso, os estudos geralmente relatam o tempo total desde a internação até a morte, o que pode aproximar a soma da duração dos estágios grave e crítico. Assim, subtraindo a duração de $I_2$,  a duração de $I_3$ pode ser estimado. A taxa de fatalidade de casos observados (CFR) descreve a fração de todos os indivíduos infectados sintomáticos que eventualmente morrem. Como os indivíduos precisam progredir para a infecção crítica para morrer, a probabilidade condicional de alguém na fase crítica morrer ou se recuperar é dada pelo CFR dividido pela fração de todas as infecções graves. Isso deve ser igual à combinação de parâmetros do modelo $\mu/(\gamma_3 + \mu)$. 

A Tabela 1 resume as fontes de literatura que usamos para estimar os valores padrão para todos esses parâmetros do modelo. Os usuários podem escolher seus próprios valores com base em outros estudos ou contextos regionais específicos.

__Table 1__:  Parâmetros estimados para a progressão clínica do COVID-19 e referências bibliográficas.

Quantidade                                 Parâmetro                              Valor        Fonte       
--------------------------------------   ---------------------                  ----------   --------------------------------------------------
Período de Incubação                         $1/a$                                 5 dias       [@li_early_2020 ; @linton_incubation_2020; @lauer_incubation_2020; @bi_epidemiology_2020; @sanche_novel_2020]
Proporção de Infecções leves             $\gamma_1/(p_1+\gamma_1)$               80%          [@wu_characteristics_2020; @yang_epidemiological_2020; @liu_nl_2020]
Duração de infecções leves               $1/(p_1+\gamma_1)$                      6 dias       Carga Viral: [@woelfel_clinical_2020], Tempo desde sintomas até internação: [@sanche_novel_2020; @tindale_transmission_2020]
Proporção de infecções graves               $\gamma_1/(p_1+\gamma_1)$             15%          [@wu_characteristics_2020; @yang_epidemiological_2020]
Tempo de sintomas até internação em UTI     --                                    12 dias      [@huang_clinical_2020; @yang_clinical_2020; @liu_nl_2020; @zhou_clinical_2020]
Duração de infecções graves                  $1/(p_2+\gamma_2)$                    6 dias       =[Tempo de sintomas até internação em UTI] - [Duração de infecções leves]
Proporção de infecções críticas           % Graves$\times p_2/(p_2+\gamma_2)$   5%           [@wu_characteristics_2020; @yang_epidemiological_2020; @liu_nl_2020]
Tempo de entrada no hospital até óbito     --                                    14 dias      [@sanche_novel_2020; @linton_incubation_2020;@zhou_clinical_2020;  @guan_clinical_2020]
Duração de infecções críticas             $1/(\mu+\gamma_3)$                    8 dias       =[Tempo de entrada no hospital até óbito] - [Duração de infecção grave] [@zhou_clinical_2020]
Tempo do surgimento de sintomas até óbito          --                              20 dias      =[Duração de infecções leves + graves + críticas][@wu_estimating_2020; @verity_estimates_2020; @zhou_clinical_2020]
Razão de fatalidade de casos              % Críticas$\times\mu/(\mu+\gamma_3)$  2%           [@wu_characteristics_2020; @russell_estimating_2020; @riou_adjusted_2020; @baud_real_2020; @wu_estimating_2020; @verity_estimates_2020]
Intervalo Serial                           $1/a + (1/2) 1/(p_1 + \gamma_1)$      8 dias       =[Período de Incubação]+1/2[Duração de infecções leves]

As taxas de transmissão normalmente são impossíveis de se observar ou estimar diretamente. No entanto, estes valores podem ser recuperados se observarmos o crescimento exponencial inicial ($r$) de uma epidemia e escolhermos taxas de transmissão que recriem essas observações. O crescimento de surtos de COVID-19 têm variado muito entre ambientes e ao longo do tempo. Alguns valores citados na literatura estão na Tabela 2. O cálculo automatizado em tempo-real de taxas de crescimento para diferentes países é disponível no [Coronavirus Forecast Shiny App](https://benflips.shinyapps.io/nCovForecast/) de Ben Phillip ou no [Centre for Mathematical Modelling of Infectious Diseases](https://cmmid.github.io/topics/covid19/current-patterns-transmission/global-time-varying-transmission.html). Os valores padrão para a simulação no momento estão definidos numa situação com $r=0.14$ [@verity_estimates_2020]. Como padrão nós presumimos que a fonte dominante de transmissão é de indivíduos com infecções leves. (e.g. $\beta_1 \gg \beta_2, \beta_3$), que provavelmente ainda estão presentes na comunidade, ao invés de isolados em internações hospitalares. 

Alguns relatos recentes sugerem que agentes de saúde são desproporcionalmente infectados por COVID-19, sugerindo que existe um papel importante realizado por transmissões dentro de hospitais (por ex., de indivíduos nos estágios $I_2$ e $I_3$, ou indivíduos que são hospitalizados apenas com infecções leves). Na China, aproximadamente 5% de todas as infecções foram em agentes de saúde [@wang_exploring_2020], e na Itália o número gira em torno de 10% [@wang_exploring_2020]. Para representar isto, decidimos incluir uma pequena contribuição de $\beta_2$ e $\beta_3$ para a transmissão de modo que, junto com os outros valores padrões pré-definidos, mais ou menos 10% do valor de $R_0$ fosse resultado da transmissão de infecções graves + críticas.

__Tabela 2__: Taxas de crescimento epidêmico inicial $r$ observadas através de diferentes cenários, junto do tempo de duplicação correspondente. Existem muitos outros cenários onde taxas de crescimento agora se aproximam de zero.

Taxa de Crescimento $r$      Tempo de Duplicação  Local        Datas              Fonte
----------------            -------------------  ------------  ------------------    -------------------------
0.1                         6.9 dias              Wuhan         Início de Janeiro     [@li_early_2020]
0.14                        5.0 dias              Wuhan         Início de Janeiro     [@verity_estimates_2020]
0.25                        2.8 dias              Wuhan           Janeiro             [@zhao_analysis_2020]
0.3                         2.3 dias              Wuhan           Janeiro            [@sanche_novel_2020]
0.5                         1.4 dias              Itália           24 Fev.           [@abbott_temporal_2020]
0.17                        4.1 dias              Itália          9 Mar.             [@abbott_temporal_2020]
0.3                         2.3 dias              Irã            2 Mar.              [@abbott_temporal_2020]
0.5                         1.4 dias              Espanha           29 Fev.          [@abbott_temporal_2020]
0.2                         3.5 dias              Espanha           9 Mar.           [@abbott_temporal_2020]
0.2                         3.5 dias              França          9 Mar.             [@abbott_temporal_2020]
0.2                         3.5 dias             Coréia do Sul    24 Fev.            [@abbott_temporal_2020]
0.5                         1.4 dias              Reino Unido       2 Mar.           [@abbott_temporal_2020]


### Parâmetros de Capacidade Hospitalar

Um dos principais perigos de uma epidemia em larga escala de COVID-19 é a carga que ela colocaria em recursos hospitalares, já que indivíduos com infecções graves e críticas necessitam de cuidado hospitalar. O estágio crítico da infecção necessita ventilação mecânica, que é tratamento de nível UTI. Infecções graves podem ser tratadas em seções normais do hospital. Indivíduos com infecções leves não requerem internação, e poderiam se recuperar sozinhos em suas casas. Entretanto, em muitos países estes indivíduos também estão sendo internados, tanto quanto forma de isolá-los e reduzir transmissão, como também para monitoramento da progressão da infecção no indivíduo para estados mais graves. 

Os parâmetros padrões para capacidade hospitalar são estimados para os Estados Unidos, e são expressados como recursos per capita. Os leitos disponíveis (regulares e UTI) dependem do número total de leitos que existem e do grau de ocupação destes. Durante a temporada de gripe (meses de inverno), níveis de ocupação normalmente são maiores. Nós relatamos o número de leitos *disponíveis* (desocupados) de ambos os tipos (Tabela 3). 
A literatura sobre estudos de preparo para pandemias têm investigado como a cpacidade de distribuir ventilação mecânica durante um surto de um patógeno respiratório poderia ser expandido além capacidade tradicional de UTIs (também dita como *capacidade convencional*) utilizando ventiladores estocados, equipe médica não-especialista, e reacomodação de outros cômodos hospitalares [@ajao_assessing_2015]. Esses níveis de entrega expandida são chamados de capacidade de *contingência* e *crise* . 

__Tabela 3__. Capacidade hospitalar nos EUA. Valores apenas para leitos adultos.

Quantidade                                        Total     A cada 100 Pessoas    Fontes
---------------------------------------------   ---------  --------------------   -----------------------
Leitos Hospitalares                             900,000     2.8                   [@nchs_table_2017]
Ocupação                                         66%                              [@nchs_table_2017]
Leitos de UTI                                   80,000      0.26                  [@sccm_2010]
Ocupação                                         68%                              [@sccm_2010]
$\uparrow$ Ocupação em temporada de gripe         7%                              [@ajao_assessing_2015]
Leitos Hospitalares disponíveis                  264,000     0.82                 Ver Acima     
Leitos de UTI disponíveis                        22,000      0.071                Ver Acima  
Capacidade de Ventilação Mecânica Convencional    20,000      0.062               [@ajao_assessing_2015]
Capacidade de Ventilação Mecânica Contingência     50,000      0.15               [@ajao_assessing_2015]
Capacidade de Ventilação Mecânica Crítica        135,000     0.24                 [@ajao_assessing_2015]

### Atualizações

#### Mar 21 2020

O modelo agora inclui a possibilidade de __infecção assintomática__. Na maioria dos  estudos originais sobre o COVID-19, quase todos os indivíduos inclusos apresentavam sintomas, já que a presença de sintomas era utilizada para determinar se esta pessoa seria submetida a um teste para COVID-19. Entretanto, é possível que alguns indivíduos sejam infectados e possam transmitir o vírus para outros sem apresentarem sintomas. Evidências recentes apontam que este é o caso, conforme novos estudos surgiram em que indivíduos assintomáticos também foram testados e receberam resultados positivos para o vírus. Nós tiramos estimativas de $f$, a fração de infecções que são sintomáticas, da literatura, e presumimos que infecções assintomáticas têm a mesma duração e mesma taxa de transmissão que infecções sintomáticas. 

O modelo agora inclui a possibilidade de __transmissão pré-sintomática__. A maioria dos modelos epidemiológicos compatartimentais presumem que o surgimento de sintomas e o início da capacidade de transmitir coincidem, mas indícios recentes sugerem que sintomas podem aparecer de modo atrasado, após o indivíduo se tornar um transmissor. Quando cargas virais são medidas ao longo do tempo em indivíduos sintomáticos, estudos mostram que elas atingem um pico no primeiro dia de sintomas, sugerindo que elas já fossem altas antes dos sintomas surgirem [@woelfel_clinical_2020]. Além disso, estudos detalhando o rastreamento de contato que rastrearam cadeias de transmissão onde ambos infectador e infectado são conhecidos encontraram que o _intervalo serial_, que é o tempo entre o surgimento de sintomas no infectador e no infectado, às vezes é menor do que o período de incubação. Isso significa que deve existir transmissão pré-sintomática. Nós modelamos isso separando o estado Exposto em duas classes, uma transmissional e outra não. Uma gama diversa de valores para a proporção de todas as transmissões que são pré-sintomáticas foram estimadas (12%-62%),  então decidimos por um valor intermediário de 25%, consistente com [@liu_contribution_2020].  Presumindo que infecções pré-sintomáticas têm a mesma taxa de transmissão que infecções sintomáticas durante o período em que são infecciosos, essa proporção corresponde a quantidade $(1/a_0)/((1/a_0)+(1/(p_1+\gamma_1)))$. Uma linha relacionada de evidências que sugere a presença de infecção pré-sintomática é que a duração média do intervalo serial é muito próxima da duração média do período de incubação em alguns estudos. Isto sugere ou um intervalo sintomático+infeccioso muito curto, ou, quantidades significativas de transmissão pré-sintomática. 



__Tabela 4__:  Parâmetros adicionais para a progressão clínica da COVID-19, e referências bibliográficas, da atualização do dia 21 de Março de 2020

Quantidade                                     Parâmetro                               Valor        Fonte       
--------------------------------------       ---------------------                   ----------   --------------------------------------------------
Porção de infecções assintomáticas           $f$                                     30%           [@bi_epidemiology_2020; @mizumoto_estimating_2020; @nishiura_estimation_2020]
Duração de infecções assintomáticas          $1/\gamma_0$                            6 Dias        =[Duração de Infecções Leves] 
Duração de infecciosidade pré-sintomática    $1/a_0$                                  2 Dias        [@liu_contribution_2020; @ganyani_estimating_2020; @du_serial_2020]
Intervalo Serial                              $1/a_0+(1/2)(1/a_1+1/(p_1 + \gamma_1))$ 7 Dias        =[Período de Incubação]+1/2[Duração de Infecções Leves][@bi_epidemiology_2020; @wu_characteristics_2020; @li_early_2020]


### Referências



