name: Test Application Build

on:
  pull_request:
    branches: 
      - master
      - stable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run application in venv
      run: |
        make serve
