name: Test Application Build

on:
  pull_request:
    branches: 
      - master
      - stable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Get farolcovid repo (master?)
        uses: ./.github/actions/farolcovid@master
      - name: Run application in venv
        run: |
          make serve
